services:
  configservice:
    build: .
    ports:
      - "5000-5100:5000-5100"  # Expose all ports from 5000 to 6000
      - "8000-8000:8000-8000"  # Expose port 8000
    volumes:
      - data:/app/data
    environment:
      - FLASK_ENV=production

volumes:
  data:
